import { IUser } from "../types/user";

export const userListMock: IUser[] = [
  {
    name: "João Silva",
    gender: "male",
    cpf: "12345678900",
    birthdate: "1990-05-10",
    email: "joao.silva@example.com",
    password: "Senha123!",
    address: {
      postalCode: "89201001",
      country: "Brasil",
      city: "Joinville",
      state: "SC",
      street: "Rua XV de Novembro",
      neighborhood: "Downtown",
      addressNumber: "100",
      complement: "Apto 101",
    },
  },
  {
    name: "Maria Oliveira",
    gender: "female",
    cpf: "23456789011",
    birthdate: "1985-09-22",
    email: "maria.oliveira@example.com",
    password: "Senha123!",
    address: {
      postalCode: "89204330",
      country: "Brasil",
      city: "Joinville",
      state: "SC",
      street: "Rua Blumenau",
      neighborhood: "Glória",
      addressNumber: "234",
    },
  },
  {
    name: "Carlos Souza",
    gender: "male",
    cpf: "34567890122",
    birthdate: "1978-03-15",
    email: "carlos.souza@example.com",
    password: "Senha123!",
    address: {
      postalCode: "89211150",
      country: "Brasil",
      city: "Joinville",
      state: "SC",
      street: "Rua Dona Francisca",
      neighborhood: "Industrial District",
      addressNumber: "456",
      complement: "Sala 3",
    },
  },
  {
    name: "Ana Lima",
    gender: "female",
    cpf: "45678901233",
    birthdate: "1992-11-03",
    email: "ana.lima@example.com",
    password: "Senha123!",
    address: {
      postalCode: "89221225",
      country: "Brasil",
      city: "Joinville",
      state: "SC",
      street: "Rua Copacabana",
      neighborhood: "Costa and Silva",
      addressNumber: "321",
    },
  },
  {
    name: "Pedro Rocha",
    gender: "male",
    cpf: "56789012344",
    birthdate: "1980-07-28",
    email: "pedro.rocha@example.com",
    password: "Senha123!",
    address: {
      postalCode: "89237320",
      country: "Brasil",
      city: "Joinville",
      state: "SC",
      street: "Rua Florianópolis",
      neighborhood: "Pirabeiraba",
      addressNumber: "89",
    },
  },
  {
    name: "Juliana Mendes",
    gender: "female",
    cpf: "67890123455",
    birthdate: "1995-02-19",
    email: "juliana.mendes@example.com",
    password: "Senha123!",
    address: {
      postalCode: "89223260",
      country: "Brasil",
      city: "Joinville",
      state: "SC",
      street: "Rua Piratuba",
      neighborhood: "Boa Vista",
      addressNumber: "543",
    },
  },
  {
    name: "Lucas Ferreira",
    gender: "male",
    cpf: "78901234566",
    birthdate: "1988-06-12",
    email: "lucas.ferreira@example.com",
    password: "Senha123!",
    address: {
      postalCode: "89218010",
      country: "Brasil",
      city: "Joinville",
      state: "SC",
      street: "Rua Santa Catarina",
      neighborhood: "Fátima",
      addressNumber: "87",
      complement: "Bloco B",
    },
  },
  {
    name: "Beatriz Costa",
    gender: "female",
    cpf: "89012345677",
    birthdate: "1991-01-30",
    email: "beatriz.costa@example.com",
    password: "Senha123!",
    address: {
      postalCode: "89230005",
      country: "Brasil",
      city: "Joinville",
      state: "SC",
      street: "Rua Otto Boehm",
      neighborhood: "Atiradores",
      addressNumber: "245",
    },
  },
  {
    name: "Renato Almeida",
    gender: "none",
    cpf: "90123456788",
    birthdate: "1975-12-25",
    email: "renato.almeida@example.com",
    password: "Senha123!",
    address: {
      postalCode: "89201230",
      country: "Brasil",
      city: "Joinville",
      state: "SC",
      street: "Rua Marquês de Olinda",
      neighborhood: "America",
      addressNumber: "78",
    },
  },
  {
    name: "Larissa Martins",
    gender: "female",
    cpf: "01234567899",
    birthdate: "1999-04-05",
    email: "larissa.martins@example.com",
    password: "Senha123!",
    address: {
      postalCode: "89204220",
      country: "Brasil",
      city: "Joinville",
      state: "SC",
      street: "Rua Timbó",
      neighborhood: "Saguaçu",
      addressNumber: "370",
    },
  },
];
